http {
    root ./www;
    
    server {
        listen 8080;
        server_name localhost;
        
        location / {
            methods GET;
        }
        
        location /old-page.html {
            return 301 /new-page.html;
        }
        
        location /google {
            return 301 https://www.google.com;
        }
        
        location /temp {
            return 302 /html/temp-location.html;
        }
    }
}
