
  server
  {
    root "www";
    listen 127.0.0.1:8080;
    index "/htmindex.html";
    autoindex on;
    server_name diana ;

    location / {
      methods GET;
    }
	 location /upload {
      return 302 /url;
    }
  
  }