http {
    autoindex on;
    client_max_body_size 0;
        index "index.html" index.html;
    cgi_bin_path "/usr/bin/python3";
    error_page 404 ./404.html;
  server {
       root "./www";
           listen 0.0.0.0:8080;
       index "fdg.html";
       autoindex off;
        server_name diana ;
        location /
        {
            methods POST;
        }
        location /upload
        {
            
        }
    }

}
