http
{
  server
  {
    root "www";
    listen 127.0.0.1:9090;
        listen 127.0.0.1:8080;
        client_max_body_size 1G;

    index "/html/index.html";
    autoindex on;
    server_name diana ;


    location /  {
      methods GET POST DELETE;
      upload on;
         upload_path "/upload";
    }
	
     location /hi {
            methods GET POST;
          autoindex off;
         upload on;
         upload_path "/upload";

    }
  }
  
}
