server 
{
  listen 127.0.0.1:8080;
	root "www";
  index "/html/index.html";

    location /cgi_bin
    {
      cgi on;
      cgi_ext .py .cpp;
      methods GET POST;
      client_max_body_size 10M;
    }
    location / {
      methods GET;
      
    }
}